/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.leoskvorc;

import hr.leoskvorc.model.MovieArchive;
import hr.leoskvorc.model.User.Role;
import hr.leoskvorc.utils.JAXBUtils;
import hr.leoskvorc.utils.MessageUtils;
import hr.leoskvorc.view.admin.DataManagementPanel;
import hr.leoskvorc.view.model.PanelMovieModel;
import hr.leoskvorc.view.user.EditMoviePanel;
import hr.leoskvorc.view.user.EditPersonPanel;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lskvo
 */
public class MoviesForm extends javax.swing.JFrame {

    private static final String ADMIN = "Administration";
    private static final String EDIT_MOVIE = "Edit movie";
    private static final String EDIT_PERSON = "Edit person";
    private static final String FILENAME = "movies.xml";
    
    private PanelMovieModel panel;
    //private DataManagementPanel panel;
    //private EditMoviePanel panel;

    /**
     * Creates new form MoviesForm
     * @param role
     */
    public MoviesForm(Role role) {
        initComponents();
        configurePanels(role);
        this.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpContent = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuApplication = new javax.swing.JMenu();
        miDownloadXML = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miLogOut = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movies");
        setPreferredSize(new java.awt.Dimension(1800, 1000));

        menuApplication.setMnemonic('A');
        menuApplication.setText("Application");

        miDownloadXML.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        miDownloadXML.setText("Download XML");
        miDownloadXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDownloadXMLActionPerformed(evt);
            }
        });
        menuApplication.add(miDownloadXML);
        menuApplication.add(jSeparator1);

        miLogOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        miLogOut.setText("Log Out");
        miLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogOutActionPerformed(evt);
            }
        });
        menuApplication.add(miLogOut);

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        menuApplication.add(miExit);

        jMenuBar1.add(menuApplication);

        menuHelp.setMnemonic('H');
        menuHelp.setText("Help");

        miAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        miAbout.setText("About");
        miAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutActionPerformed(evt);
            }
        });
        menuHelp.add(miAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miDownloadXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDownloadXMLActionPerformed
        try {
            JAXBUtils.save(new MovieArchive(panel.getMovies()), FILENAME);
            MessageUtils.showInformationMessage("Info", "Papers saved.");
        } catch (Exception ex) {
            Logger.getLogger(MoviesForm.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Error", "Unable to save movies");
        }

    }//GEN-LAST:event_miDownloadXMLActionPerformed

    private void miLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogOutActionPerformed
        new RegisterLogInForm().show();
        dispose();
    }//GEN-LAST:event_miLogOutActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miExitActionPerformed

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        MessageUtils.showInformationMessage("Abuot", "Upcoming movies application.");
    }//GEN-LAST:event_miAboutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuApplication;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miDownloadXML;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miLogOut;
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables

    private void configurePanels(Role role) {
        if (role == Role.ADMIN) {
            loadAdminPanels();
        }
        if (role == Role.USER) {
            roleUserPanels();
        }
    }

    private void loadAdminPanels() {
        panel = new DataManagementPanel();
        tpContent.add(ADMIN, panel);
    }

    private void roleUserPanels() {
        panel = new EditMoviePanel();
        tpContent.add(EDIT_MOVIE, panel);
        tpContent.add(EDIT_PERSON, new EditPersonPanel());
    }

}
